In [1]:
import numpy as np

In [2]:
j=[5,6,7,8,9]
j

[5, 6, 7, 8, 9]

In [5]:
y=np.array(j)
y

array([5, 6, 7, 8, 9])

In [6]:
type(y)

numpy.ndarray

In [4]:
tuple(j)

(5, 6, 7, 8, 9)

In [7]:
y

array([5, 6, 7, 8, 9])

In [8]:
y.shape

(5,)

In [9]:
y.ndim

1

In [11]:
y.size

5

In [26]:
h=y.reshape(5,1)
h

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [27]:
h.shape

(5, 1)

In [28]:
h.size

5

In [29]:
h.ndim

2

In [31]:
i=y.reshape(1,5)
i

array([[5, 6, 7, 8, 9]])

In [33]:
i.reshape
i


array([[5, 6, 7, 8, 9]])

In [34]:
i.size

5

In [35]:
i.ndim

2

In [16]:
u=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
u

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [17]:
type(u)

list

In [19]:
arr1=np.array(u)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [20]:
arr1.shape

(5, 4)

In [21]:
arr1.size

20

In [22]:
arr1.ndim

2

In [36]:
arr1.reshape(10,2)

array([[ 4,  8],
       [90, 12],
       [56, 78],
       [54, 20],
       [67, 89],
       [50, 49],
       [77, 88],
       [22, 55],
       [90, 40],
       [70, 60]])

In [40]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [41]:
k.size

20

In [42]:
k.shape

(2, 2, 5)

In [43]:
k.ndim


3

In [44]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [45]:
y.ndim

1

In [47]:
z=arr1.reshape(1,20)
z

array([[ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55,
        90, 40, 70, 60]])

In [48]:
z.ndim

2

In [49]:
arr1.shape

(5, 4)

In [50]:
arr1.reshape(2,2,5,1)

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [52]:
m=[3,4,56,7,8,9,10,11,12]
m

[3, 4, 56, 7, 8, 9, 10, 11, 12]

In [53]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [55]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [57]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [58]:
tuple(range(-10,1))

(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0)

In [59]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [60]:
range(-1,-10)

range(-1, -10)

In [61]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [62]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [63]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [64]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [65]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [66]:
range(5,50,5)

range(5, 50, 5)

In [69]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [72]:
j=[5,87,23,46,62,84,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 45, 77, 33, 80]

In [91]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else: 
        y.append(j[i])

In [92]:
for i in j:
    print(i)


5
87
23
46
62
84
45
77
33
80


In [93]:
range(len(j))

range(0, 10)